# Shared default parameters and variables
defaults: &defaults
  working_directory: ~/root/project
  resource_class: large
  docker:
    - image: cimg/android:2022.12.1

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build -x detekt

workflows:
  build:
    jobs:
      - build
